### ISSUE TITLE
Make Mac Adress not required in devices

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen#7]
In order the register process to work in 2 steps we should be able to `POST` a new device without mac_address and later add it or updated over a `PATCH`. Ensure devices with no mac_address have `state: not_configured`

http://new-apidocs.smartcitizen.me/#add-a-device

https://github.com/fablabbcn/smartcitizen/blob/723d0117238d7ca86b757bd738025458e523795c/app/models/device.rb#L9

**Comment by johnrees** [comment]
https://github.com/fablabbcn/smartcitizen/commit/314bfecd3301b48ec7595617792504a00abf0d22
